### ISSUE TITLE
Make size options visible in circle and square

### ISSUE THREAD

**Issue by danroxha** [AlexanderVanhee/Gradia#99]
Maybe it's a bug, but I think this feature makes sense in the draw square and draw circle tools

https://github.com/user-attachments/assets/c1c857af-44e6-408b-aec1-865b741df2a5

**Comment by danroxha** [comment]
I played around with the blueprint, in this moment I don't have time to learn GTK devtools

```py
# Maybe a config like this?
ToolConfig(DrawingMode.SQUARE, "box-small-outline-symbolic", 0, 1, ["fill", "size"], "stroke"),
```
Binding
```py
tools_group: Adw.PreferencesGroup = Gtk.Template.Child()
# [ ... ]
for tool in self.tools_group: 
    # I don't know how to access the name or ID of this object to use dynamic visibility
    tool.set_visible(True)
```

```css
using Gtk 4.0;
using Adw 1;

template $GradiaDrawingToolsGroup: Adw.PreferencesGroup {
  title: _("Annotation Tools");

  Adw.PreferencesGroup tools_group {
    Adw.ActionRow size_setting_row {
      child: Stack size_setting_stack {
        transition-type: crossfade;
        transition-duration: 300;
        margin-top: 8;
        margin-bottom: 8;
        margin-start: 12;
        margin-end: 12;
        valign: center;

        StackPage size_setting_page {
          name: "size";

          child: Box size_setting_container {
            orientation: horizontal;
            spacing: 6;

            Label size_setting_label {
              label: _("Size");
              halign: start;
              hexpand: true;
            }

            Box size_setting_suffix_box {
              orientation: horizontal;
              spacing: 6;
              valign: center;

              Scale size_setting_scale {
                orientation: horizontal;
                width-request: 50;
                hexpand: true;
                draw-value: true;
                value-pos: right;
                digits: 0;

                adjustment: Adjustment size_setting_adjustment {
                  lower: 1;
                  upper: 10;
                  value: 3;
                  step-increment: 1;
                  page-increment: 5;
                };

                value-changed => $_on_size_changed();
              }
            }
          };
        }
      };
    }

    Adw.ActionRow fill_font_row {
      child: Stack fill_font_stack {
        transition-type: crossfade;
        transition-duration: 300;
        margin-top: 8;
        margin-bottom: 8;
        margin-start: 12;
        margin-end: 12;
        valign: center;

        StackPage fill_color_page {
          name: "fill";

          child: Box fill_color_container {
            orientation: horizontal;
            spacing: 6;

            Label fill_color_label {
              label: _("Fill Color");
              halign: start;
              hexpand: true;
            }

            Box fill_color_suffix_box {
              orientation: horizontal;
              spacing: 6;
              valign: center;

              Button reset_button {
                icon-name: "edit-clear-symbolic";
                tooltip-text: _("Reset Fill");
                clicked => $_on_reset_fill_clicked();

                styles [
                  "flat",
                ]
              }

              ColorButton fill_color_button {
                use-alpha: true;
                color-set => $_on_fill_color_set();
              }
            }
          };
        }
      };
    }

    Adw.ActionRow font_page_row {
      child: Stack font_page_stack {
        transition-type: crossfade;
        transition-duration: 300;
        margin-top: 8;
        margin-bottom: 8;
        margin-start: 12;
        margin-end: 12;
        valign: center;

        StackPage font_page {
          name: "font";

          child: Box font_container {
            orientation: horizontal;
            spacing: 6;

            Label font_label {
              label: _("Font");
              halign: start;
              hexpand: true;
            }

            Box font_suffix_box {
              orientation: horizontal;
              spacing: 6;
              valign: center;

              DropDown font_dropdown {
                selected: 0;
                width-request: 150;

                model: StringList font_string_list {};

                factory: SignalListItemFactory font_factory {
                  setup => $_font_factory_setup();
                  bind => $_font_factory_bind();
                };

                notify::selected => $_on_font_selected();
              }
            }
          };
        }
      };
    }

    Adw.ActionRow stack_row {
      child: Stack number_radius_stack {
        transition-type: crossfade;
        transition-duration: 300;
        margin-top: 8;
        margin-bottom: 8;
        margin-start: 12;
        margin-end: 12;
        valign: center;

        StackPage number_radius_page {
          name: "number_radius";

          child: Box number_radius_container {
            orientation: horizontal;
            spacing: 6;

            Label number_radius_label {
              label: _("Radius");
              halign: start;
              hexpand: true;
            }

            Box number_radius_suffix_box {
              orientation: horizontal;
              spacing: 6;
              valign: center;

              Scale number_radius_scale {
                orientation: horizontal;
                width-request: 50;
                hexpand: true;
                draw-value: true;
                value-pos: right;
                digits: 0;

                adjustment: Adjustment number_radius_adjustment {
                  lower: 10;
                  upper: 40;
                  value: 15;
                  step-increment: 5;
                  page-increment: 5;
                };

                value-changed => $_on_number_radius_changed();
              }
            }
          };
        }
      };
    }

    Adw.ActionRow color_stack_row {
      child: Stack color_stack {
        transition-type: crossfade;
        transition-duration: 300;
        margin-top: 8;
        margin-bottom: 8;
        margin-start: 12;
        margin-end: 12;
        valign: center;

        StackPage stroke_color_page {
          name: "stroke";

          child: Box stroke_color_container {
            orientation: horizontal;
            spacing: 6;

            Label stroke_color_label {
              label: _("Color");
              halign: start;
              hexpand: true;
            }

            Box stroke_color_suffix_box {
              orientation: horizontal;
              spacing: 6;
              valign: center;

              ColorButton stroke_color_button {
                valign: center;
                color-set => $_on_pen_color_set();
              }
            }
          };
        }

        StackPage highlighter_color_page {
          name: "highlighter";

          child: Box highlighter_color_container {
            orientation: horizontal;
            spacing: 6;

            Label highlighter_color_label {
              label: _("Highlighter Color");
              halign: start;
              hexpand: true;
            }

            Box highlighter_color_suffix_box {
              orientation: horizontal;
              spacing: 6;
              valign: center;

              ColorButton highlighter_color_button {
                valign: center;
                use-alpha: true;
                color-set => $_on_highlighter_color_set();
              }
            }
          };
        }
      };
    }
  }
}
```
